### ISSUE TITLE
`global-variable` check should not flag constants.

### ISSUE THREAD

**Issue by erikwright** [Shopify/shopify_python#13]
https://google.github.io/styleguide/pyguide.html#Global_variables

> Some exceptions are ... Module-level constants. For example: PI = 3.14159. Constants should be named using all caps with underscores; see Naming below.

**Comment by cfournie** [comment]
Fixed by https://github.com/Shopify/shopify_python/pull/14 and https://github.com/Shopify/shopify_python/pull/16
