### ISSUE TITLE
update the `global-variable` check to not flag type aliases

### ISSUE THREAD

**Issue by erikwright** [Shopify/shopify_python#9]
When a type is defined in some way besides a direct class definition (for example, from the return value of `namedtuple` or a `typing` construct) it should not require disabling any checks.

Two ways to achieve this:
* Ideally, we would know that the return value of the expression is a `type` instance. If we have type annotations for the operation we might be able to achieve that.
* Otherwise, we should have a regex in the config for valid classnames. We could choose not to trigger on variables whose names match that regex.

**Comment by cfournie** [comment]
Would a whitelist of modules whose functions could be allowed to be assigned to globals be sufficient? E.g. we could allow `typing `'s and `collections`'s functions to assign to globals. If we wanted to be even more specific we could limit by module and function name, e.g. `collections.namedtuple` and `typing.*`.

**Comment by erikwright** [comment]
@cfournie It's OK but not ideal. For example, one could imagine defining a type in one place and then re-referencing it elsewhere.

And I already know of at least one other method we call to generate types (in `future`, for specifying a metaclass with Py2/3 compatibility).

**Comment by cfournie** [comment]
Fixed by https://github.com/Shopify/shopify_python/pull/14
